// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOp3EcqXSZQRvm-lirQuJqc7GEs2M1-6k',
    appId: '1:387926354040:web:8a10c14a828f8a39a6a58d',
    messagingSenderId: '387926354040',
    projectId: 'aspiranchat',
    authDomain: 'aspiranchat.firebaseapp.com',
    storageBucket: 'aspiranchat.appspot.com',
    measurementId: 'G-YDTFJJE25K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRuyV4KyaojN4sPkEGoul0_R0jHlcF73k',
    appId: '1:387926354040:android:e3388f9c9d70041ba6a58d',
    messagingSenderId: '387926354040',
    projectId: 'aspiranchat',
    storageBucket: 'aspiranchat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM0ER1xfy2ycbG14Bk0lmKC0v0oG3RzWs',
    appId: '1:387926354040:ios:992f35a9a14e6fb1a6a58d',
    messagingSenderId: '387926354040',
    projectId: 'aspiranchat',
    storageBucket: 'aspiranchat.appspot.com',
    androidClientId: '387926354040-rc6prjv98u33q6dbob1ff11a9a5g3157.apps.googleusercontent.com',
    iosClientId: '387926354040-k0nigjk1if3448uaaee2d7brocoqc2qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM0ER1xfy2ycbG14Bk0lmKC0v0oG3RzWs',
    appId: '1:387926354040:ios:05f7dd272f443f13a6a58d',
    messagingSenderId: '387926354040',
    projectId: 'aspiranchat',
    storageBucket: 'aspiranchat.appspot.com',
    androidClientId: '387926354040-rc6prjv98u33q6dbob1ff11a9a5g3157.apps.googleusercontent.com',
    iosClientId: '387926354040-9uk3vifs59uld7il6d9ui9hbboaq68sd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
